---
- name: 서비스 생성 및 배포
  hosts: localhost
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      become: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started

    - name: Pull Docker Image
      docker_image:
        name: nginx:latest
        state: present

    - name: Deploy Docker Service
      docker_service:
        name: my_nginx
        state: started
        published_ports:
          - "80:80"
